import ru.itmo.task1.model.CustomerRequest;
global CustomerRequest customerRequest;

dialect "mvel"

rule "Happy birthday points"
    when
        CustomerRequest(isBirthdayToday() == true)
    then
        customerRequest.setPoints(2000);
end

rule "No points"
    when
        CustomerRequest(getPurchasesAmount() < 100)
    then
        customerRequest.setPoints(0);
end

rule "+ 100 points"
    when
        CustomerRequest(getPurchasesAmount() >= 100 && getPurchasesAmount() <= 500)
    then
        customerRequest.setPoints(100);
end

rule "+ 500 points"
    when
        CustomerRequest(getPurchasesAmount() > 500 && getPurchasesAmount() <= 1000)
    then
        customerRequest.setPoints(500);
end

rule "+ 1000 points"
    when
        CustomerRequest(getPurchasesAmount() > 1000)
    then
        customerRequest.setPoints(1000);
end

